# Generated by Django 5.2.11 on 2026-04-22 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Type Employé',
                'verbose_name_plural': 'Types Employé',
                'db_table': 'type_employe',
            },
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
                'db_table': 'administrateur',
            },
        ),
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('en_cours', 'En Cours'), ('termine', 'Terminé'), ('archive', 'Archivé')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to='core.administrateur')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'db_table': 'dossier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarteIA_Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField()),
                ('mots_cles', models.JSONField(default=list)),
                ('analyse', models.TextField(blank=True)),
                ('entites', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carte_ia', to='core.dossier')),
            ],
            options={
                'verbose_name': 'Carte IA Dossier',
                'verbose_name_plural': 'Cartes IA Dossiers',
                'db_table': 'carte_ia_dossier',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('avatar', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL)),
                ('type_employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='core.typeemploye')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'db_table': 'employe',
            },
        ),
        migrations.CreateModel(
            name='Fichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='fichiers/%Y/%m/')),
                ('type_fichier', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel'), ('image', 'Image'), ('autre', 'Autre')], default='autre', max_length=10)),
                ('taille', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='core.dossier')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichiers_uploades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fichier',
                'verbose_name_plural': 'Fichiers',
                'db_table': 'fichier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('type_notif', models.CharField(choices=[('info', 'Info'), ('warning', 'Avertissement'), ('success', 'Succès'), ('error', 'Erreur')], default='info', max_length=20)),
                ('lu', models.BooleanField(default=False)),
                ('lien', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoumissionFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='soumissions/%Y/%m/')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('en_attente', 'En Attente'), ('approuve', 'Approuvé'), ('rejete', 'Rejeté')], default='en_attente', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='core.dossier')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soumissions', to='core.employe')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soumissions_revues', to='core.administrateur')),
            ],
            options={
                'verbose_name': 'Soumission Fichier',
                'verbose_name_plural': 'Soumissions Fichiers',
                'db_table': 'soumission_fichier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acces', models.CharField(choices=[('lecture', 'Lecture'), ('ecriture', 'Écriture'), ('admin', 'Admin')], default='lecture', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accordee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_accordees', to='core.administrateur')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.dossier')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='core.employe')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permission',
                'unique_together': {('employe', 'dossier')},
            },
        ),
    ]
