# Generated by Django 5.2.11 on 2026-05-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='type_dossier',
            field=models.CharField(choices=[('enterprise', 'Entreprise'), ('bills', 'Factures'), ('hr', 'RH'), ('reports', 'Rapports')], default='enterprise', max_length=20),
        ),
        migrations.AddField(
            model_name='fichier',
            name='ai_resume',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='ai_titre',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
