# Generated by Django 5.2.11 on 2026-05-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dossier_type_dossier_fichier_ai_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierTypeCustom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('color', models.CharField(default='#6366F1', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dossier_type_custom',
                'ordering': ['created_at'],
            },
        ),
    ]
