# Generated by Django 5.2.11 on 2026-05-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dossiertypecustom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='type_dossier',
            field=models.CharField(default='enterprise', max_length=50),
        ),
    ]
