# Generated by Django 5.2.11 on 2026-05-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_type_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteia_dossier',
            name='resume_structure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
