# Generated by Django 5.2.11 on 2026-05-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carteia_dossier_resume_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soumissionfichier',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='soumissions/%Y/%m/'),
        ),
    ]
