# Generated by Django 5.2.11 on 2026-05-09 14:49

from django.db import migrations, models


def add_soumission_column(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute(
            "ALTER TABLE fichier ADD COLUMN soumission_id INTEGER NULL DEFAULT NULL;"
        )
    else:
        schema_editor.execute(
            "ALTER TABLE fichier "
            "ADD COLUMN soumission_id INT NULL DEFAULT NULL, "
            "ADD CONSTRAINT fichier_soumission_fk "
            "FOREIGN KEY (soumission_id) REFERENCES soumission_fichier(id) ON DELETE SET NULL;"
        )


def remove_soumission_column(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        schema_editor.execute("ALTER TABLE fichier DROP COLUMN soumission_id;")
    else:
        schema_editor.execute(
            "ALTER TABLE fichier "
            "DROP FOREIGN KEY fichier_soumission_fk, "
            "DROP COLUMN soumission_id;"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_soumission_fichier_optional'),
    ]

    operations = [
        # Use RunSQL because existing tables use INT PKs while DEFAULT_AUTO_FIELD=BigAutoField
        # would generate a BIGINT FK column that MySQL rejects as incompatible.
        migrations.RunSQL(
            sql="ALTER TABLE fichier ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'confirme';",
            reverse_sql="ALTER TABLE fichier DROP COLUMN status;",
        ),
        migrations.RunPython(
            code=add_soumission_column,
            reverse_code=remove_soumission_column,
        ),
        # Keep the Django state in sync
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='fichier',
                    name='status',
                    field=models.CharField(
                        choices=[('confirme', 'Confirmé'), ('en_attente', 'En attente')],
                        default='confirme',
                        max_length=20,
                    ),
                ),
                migrations.AddField(
                    model_name='fichier',
                    name='soumission',
                    field=models.ForeignKey(
                        blank=True, null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name='fichiers_soumis',
                        to='core.soumissionfichier',
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
