# Generated by Django 5.2.11 on 2026-05-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_fichier_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/admins/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/employes/%Y/%m/'),
        ),
    ]
